bitmap.c
ALGIF_BITMAP* algif_create_bitmap(int w, int h)
References ALGIF_BITMAP::data, ALGIF_BITMAP::h, ALGIF_BITMAP::w.
Referenced by algif_load_raw, deinterlace.
void algif_destroy_bitmap(ALGIF_BITMAP *bitmap)
References ALGIF_BITMAP::data.
Referenced by algif_destroy_animation, algif_load_raw, deinterlace.
void algif_blit(ALGIF_BITMAP *from, ALGIF_BITMAP *to, int xf, int yf, int xt, int yt, int w, int h)
References ALGIF_BITMAP::data, ALGIF_BITMAP::h, ALGIF_BITMAP::w.
Referenced by deinterlace.