Hitbox
double Hitbox::radius
Referenced by CalculateCollision, ship::CalculateCollisions, Hitbox.
HitboxType Hitbox::type
Referenced by CalculateCollision, Hitbox.
std::unique_ptr<double> Hitbox::posX
Referenced by Bullet::calculate, CalculateCollision, ship::CalculateCollisions, Enemy::calculatePosition, Player::calculatePosition, ship::GetX, Enemy::GetX, GetX, Player::GetX, Hitbox, HitboxHELPME.
std::unique_ptr<double> Hitbox::posY
Referenced by Bullet::Bullet, Bullet::calculate, CalculateCollision, ship::CalculateCollisions, Enemy::calculatePosition, Player::calculatePosition, ship::GetY, Enemy::GetY, GetY, Player::GetY, Hitbox, HitboxHELPME.
double Hitbox::boundryX
Referenced by Object::CollisionCalculate, Hitbox.
double Hitbox::boundryY
Referenced by Object::CollisionCalculate, Hitbox.
Hitbox::Hitbox()
Hitbox::Hitbox(double x, double y)
References dot, posX, posY, type.
Hitbox::Hitbox(double x, double y, double radius)
References circle, posX, posY, radius, type.
Hitbox::Hitbox(double x, double y, double boundryX, double boundryY)
References boundryX, boundryY, posX, posY, square, type.
void Hitbox::HitboxHELPME(double x, double y, bool flag)
References posX, posY.
double Hitbox::GetX()
References posX.
Referenced by Bullets::CalcuclateBulletsCollision, Bullets::DrawBullets, Bullets::DrawBulletstest.
double Hitbox::GetY()
References posY.
Referenced by Bullets::CalcuclateBulletsCollision, Bullets::DrawBullets, Bullets::DrawBulletstest.
bool Hitbox::CalculateCollision(Hitbox *second)
References circle, dot, posX, posY, radius, square, type.
Referenced by Bullets::CalcuclateBulletsCollision.
bool Hitbox::CalculateCollision(HitboxType sType, double sPosX, double sPosY, double sRadius)
References circle, dot, posX, posY, radius, square, type.
Hitbox::~Hitbox()