Game
int Game::result
Referenced by Game.
Game::Game()
References mainloop, result.
Game::~Game()
void * Game::Func_ThreadBulletsCalculations(ALLEGRO_THREAD *thr, void *arg)
References DATA::AddEnemy, Bullets::CalculateBulletsV2, DATA::calculateEnemies, DATA::ClearDeadEnemies, DATA::counter, PI, DATA::Playerbullets, DATA::ready, TicsForEnemySpawn, WindowWidth.
Referenced by mainloop.
int Game::mainloop()
References Bullets::AddBullet, Bullets::CalculateBullets, Player::CalculateCollisionsForPlayer, Player::calculatePosition, Object::ChangeBitmap, DATA::counter, Bullets::DrawBullets, DATA::DrawEnemies, Player::DrawPlayer, DATA::enemyBullets, FPScount, Func_ThreadBulletsCalculations, Object::GetBitmap, ship::GetHealth, Player::GetX, Player::GetY, PI, player, DATA::player, PlayerDmg, PlayerHealth, Player::PlayerShot, programName, DATA::ready, Bullets::setDmg, Player::SetDown, Player::SetLeft, Player::SetRight, Player::SetShooting, Player::SetUp, WindowHeight, WindowWidth.
Referenced by Game, main.