DATA
ALLEGRO_MUTEX* DATA::mutex
Referenced by DATA, ~DATA.
ALLEGRO_COND* DATA::cond
Referenced by DATA, ~DATA.
Bullets* DATA::Playerbullets
Referenced by calculateEnemies, DATA, Game::Func_ThreadBulletsCalculations.
Bullets * DATA::enemyBullets
Referenced by calculateEnemies, DATA, Game::mainloop.
Player* DATA::player
Referenced by DATA, Game::mainloop.
int DATA::counter
Referenced by DATA, Game::Func_ThreadBulletsCalculations, Game::mainloop.
std::vector< Enemy * > DATA::enemies
Referenced by AddEnemy, calculateEnemies, ClearDeadEnemies, DrawEnemies.
bool DATA::ready
Referenced by DATA, Game::Func_ThreadBulletsCalculations, Game::mainloop.
DATA::DATA(Bullets *Playerbullets, Bullets *enemyBullets, Player *player)
References cond, counter, enemyBullets, mutex, player, Playerbullets, ready.
DATA::~DATA()
References cond, mutex.
void DATA::AddEnemy(const char *filename, int x, int y, double speed, int period)
References enemies, enemy.
Referenced by Game::Func_ThreadBulletsCalculations.
void DATA::AddEnemy(const char *filename, int x, int y, double speed, double(*f2)(double x), int period)
References enemies, enemy.
void DATA::DrawEnemies()
References enemies, PI.
Referenced by Game::mainloop.
void DATA::calculateEnemies(int timer)
References enemies, enemyBullets, Playerbullets.
Referenced by Game::Func_ThreadBulletsCalculations.
void DATA::ClearDeadEnemies()
References enemies.
Referenced by Game::Func_ThreadBulletsCalculations.