Object
int Object::sizeX
Referenced by DrawObject, Object.
int Object::sizeY
Referenced by DrawObject, Object.
MyBitmap* Object::bitmapa
Referenced by ChangeBitmap, GetBitmap, Object, ~Object.
void Object::DrawObject(int x, int y, double rotation=0, float scale=1)
References GetBitmap, sizeX, sizeY.
Referenced by Bullets::DrawBullets, Enemy::DrawEntity, ship::DrawShip.
void Object::DrawObjecttest(int x, int y, double rotation=0, int scale=1)
References GetBitmap.
Referenced by Bullets::DrawBulletstest.
Object::Object(const char *filename)
References bitmapa, MyBitmap::image, sizeX, sizeY.
Object::Object(const char *filename, int posX, int posY, int x)
References bitmapa, MyBitmap::image, sizeX, sizeY.
Object::Object(const char *filename, int posX, int posY, int x, int y)
References bitmapa, MyBitmap::image, sizeX, sizeY.
Object::Object(const char *filename, int posX, int posY, int x, int y, double sizeX)
Object::Object(const char *filename, int posX, int posY, Hitbox *hitbox)
Object::Object(const char *filename, int posX, int posY, int x, int y, Hitbox *hitbox)
Object::Object(Hitbox *hitbox)
Object::Object(int x, int y, Hitbox *hitbox)
void Object::ChangeBitmap(const char *filename)
References bitmapa, MyBitmap::ChangeBitmap.
Referenced by Game::mainloop.
bool Object::CollisionCalculate(double x, double y, double objX, double objY, int objBouncerX, int objBouncerY)
References Hitbox::boundryX, Hitbox::boundryY.
Referenced by Bullets::CalcuclateBulletsCollision.
ALLEGRO_BITMAP * Object::GetBitmap()
References bitmapa, MyBitmap::image.
Referenced by DrawObject, DrawObjecttest, Game::mainloop.
int Object::GetSizeX()
int Object::GetSizeY()
Object::Object()
Object::~Object()
References bitmapa.