gif.c
int LZW_decode(ALLEGRO_FILE *file, ALGIF_BITMAP *bmp)
References ALGIF_BITMAP::data, read_code.
Referenced by algif_load_raw.
void algif_destroy_animation(ALGIF_ANIMATION *gif)
References algif_destroy_bitmap, ALGIF_FRAME::bitmap_8_bit, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_FRAME::rendered, ALGIF_ANIMATION::store.
Referenced by algif_load_raw.
static void read_palette(ALLEGRO_FILE *file, ALGIF_PALETTE *palette)
References ALGIF_RGB::b, ALGIF_PALETTE::colors, ALGIF_PALETTE::colors_count, ALGIF_RGB::g, ALGIF_RGB::r.
Referenced by algif_load_raw.
static void deinterlace(ALGIF_BITMAP *bmp)
References algif_blit, algif_create_bitmap, algif_destroy_bitmap, ALGIF_BITMAP::h, ALGIF_BITMAP::w.
Referenced by algif_load_raw.
ALGIF_ANIMATION* algif_load_raw(ALLEGRO_FILE *file)
References algif_create_bitmap, algif_destroy_animation, algif_destroy_bitmap, ALGIF_ANIMATION::background_index, ALGIF_FRAME::bitmap_8_bit, ALGIF_PALETTE::colors_count, deinterlace, ALGIF_FRAME::disposal_method, ALGIF_FRAME::duration, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_ANIMATION::height, ALGIF_ANIMATION::loop, LZW_decode, ALGIF_ANIMATION::palette, ALGIF_FRAME::palette, read_palette, ALGIF_FRAME::transparent_index, ALGIF_ANIMATION::width, ALGIF_FRAME::xoff, ALGIF_FRAME::yoff.
Referenced by algif_load_animation_f.