algif.h
typedef struct ALGIF_ANIMATION ALGIF_ANIMATION
typedef struct ALGIF_FRAME ALGIF_FRAME
typedef struct ALGIF_PALETTE ALGIF_PALETTE
typedef struct ALGIF_BITMAP ALGIF_BITMAP
typedef struct ALGIF_RGB ALGIF_RGB
ALGIF_ANIMATION* algif_load_raw(ALLEGRO_FILE *file)
References algif_create_bitmap, algif_destroy_animation, algif_destroy_bitmap, ALGIF_ANIMATION::background_index, ALGIF_FRAME::bitmap_8_bit, ALGIF_PALETTE::colors_count, deinterlace, ALGIF_FRAME::disposal_method, ALGIF_FRAME::duration, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_ANIMATION::height, ALGIF_ANIMATION::loop, LZW_decode, ALGIF_ANIMATION::palette, ALGIF_FRAME::palette, read_palette, ALGIF_FRAME::transparent_index, ALGIF_ANIMATION::width, ALGIF_FRAME::xoff, ALGIF_FRAME::yoff.
Referenced by algif_load_animation_f.
ALGIF_ANIMATION* algif_load_animation_f(ALLEGRO_FILE *file)
References algif_load_raw, algif_render_frame, ALGIF_ANIMATION::duration, ALGIF_FRAME::duration, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_ANIMATION::height, ALGIF_FRAME::rendered, ALGIF_ANIMATION::width.
Referenced by algif_load_animation.
ALGIF_ANIMATION* algif_load_animation(char const *filename)
References algif_load_animation_f.
void algif_render_frame(ALGIF_ANIMATION *gif, int frame, int xpos, int ypos)
References ALGIF_RGB::b, ALGIF_FRAME::bitmap_8_bit, ALGIF_PALETTE::colors, ALGIF_PALETTE::colors_count, ALGIF_BITMAP::data, ALGIF_FRAME::disposal_method, ALGIF_ANIMATION::frames, ALGIF_RGB::g, ALGIF_BITMAP::h, ALGIF_ANIMATION::height, ALGIF_ANIMATION::palette, ALGIF_FRAME::palette, ALGIF_RGB::r, ALGIF_ANIMATION::store, ALGIF_FRAME::transparent_index, ALGIF_BITMAP::w, ALGIF_ANIMATION::width, ALGIF_FRAME::xoff, ALGIF_FRAME::yoff.
Referenced by algif_load_animation_f.
void algif_destroy_animation(ALGIF_ANIMATION *gif)
References algif_destroy_bitmap, ALGIF_FRAME::bitmap_8_bit, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_FRAME::rendered, ALGIF_ANIMATION::store.
Referenced by algif_load_raw.
ALGIF_BITMAP* algif_create_bitmap(int w, int h)
References ALGIF_BITMAP::data, ALGIF_BITMAP::h, ALGIF_BITMAP::w.
Referenced by algif_load_raw, deinterlace.
void algif_destroy_bitmap(ALGIF_BITMAP *bitmap)
References ALGIF_BITMAP::data.
Referenced by algif_destroy_animation, algif_load_raw, deinterlace.
void algif_blit(ALGIF_BITMAP *from, ALGIF_BITMAP *to, int xf, int yf, int xt, int yt, int w, int h)
References ALGIF_BITMAP::data, ALGIF_BITMAP::h, ALGIF_BITMAP::w.
Referenced by deinterlace.
ALLEGRO_BITMAP* algif_get_bitmap(ALGIF_ANIMATION *gif, double seconds)
References ALGIF_ANIMATION::duration, ALGIF_FRAME::duration, ALGIF_ANIMATION::frames, ALGIF_ANIMATION::frames_count, ALGIF_FRAME::rendered.
ALLEGRO_BITMAP* algif_get_frame_bitmap(ALGIF_ANIMATION *gif, int i)
References ALGIF_ANIMATION::frames, ALGIF_FRAME::rendered.
double algif_get_frame_duration(ALGIF_ANIMATION *gif, int i)
References ALGIF_FRAME::duration, ALGIF_ANIMATION::frames.