ship
int ship::rotation
double ship::speed
Referenced by GetSpeed, ship.
int ship::health
Referenced by CalculateCollisions, GetHealth, Enemy::GetHealth, Enemy::GetHealthAndBoundarys, ship.
Weapons* ship::playerWeapons
Referenced by ship, ~ship.
ship::ship()
References player, playerWeapons, speed.
ship::ship(const char *filename, int x, int y, int radius, int health)
References health, player, playerWeapons, speed.
ship::ship(const char *filename, int x, int y, int radius, double s, int health)
References health, player, playerWeapons, speed.
bool ship::CalculateCollisions(Bullets *bullets)
References Bullets::bullets, Bullets::damage, health, Hitbox::posX, Hitbox::posY, Hitbox::radius.
Referenced by Player::CalculateCollisionsForPlayer.
int ship::GetHealth()
References health.
Referenced by Game::mainloop.
double ship::GetX()
References Hitbox::posX.
double ship::GetY()
References Hitbox::posY.
double ship::GetSpeed()
References speed.
Referenced by Enemy::calculatePosition, Player::calculatePosition.
ship::~ship()
References playerWeapons.
void ship::DrawShip(int x, int y, int rotation=0, int scale=1)
References Object::DrawObject.
Referenced by Player::DrawPlayer.