Bullets
std::vector< Bullet * > Bullets::bullets
Referenced by AddBullet, CalcuclateBulletsCollision, CalculateBullets, CalculateBulletsV2, ship::CalculateCollisions, DrawBullets, DrawBulletstest, GetBullets, ~Bullets.
int Bullets::damage
Referenced by ship::CalculateCollisions, setDmg.
double(* Bullets::f)(double))(double)
Referenced by Bullets.
Bullets::Bullets(const char *filename, double(*f)(double))
References f.
Bullets::Bullets(const char *filename)
Bullets::Bullets()
void Bullets::AddBullet(double rotation, double posX, double posY, double speedX, double speedY)
References bullets.
Referenced by Enemy::EntityShot, Game::mainloop, Player::PlayerShot.
void Bullets::AddBullet(double rotation, double posX, double posY, double speedX, double speedY, double sizeX)
References bullets.
void Bullets::AddBullet(double rotation, double posX, double posY, double speedX, double speedY, double sizeX, double sizeY)
References bullets.
void Bullets::setDmg(int value)
References damage.
Referenced by Game::mainloop.
void Bullets::CalculateBullets()
References bullets.
Referenced by Game::mainloop.
void Bullets::CalculateBulletsV2(double f2(double x))
References bullets.
Referenced by Game::Func_ThreadBulletsCalculations.
void Bullets::CalcuclateBulletsCollision(double posX, double posY, int objBouncerX, int objBouncerY)
References bullets, Object::CollisionCalculate, Hitbox::GetX, Hitbox::GetY.
int Bullets::CalcuclateBulletsCollision(Hitbox *hitbox)
References bullets, Hitbox::CalculateCollision.
void Bullets::ClearBulletsByCollision()
void Bullets::DrawBullets(float scale=1)
References bullets, Object::DrawObject, Hitbox::GetX, Hitbox::GetY.
Referenced by Game::mainloop.
void Bullets::DrawBulletstest(float scale=1)
References bullets, Object::DrawObjecttest, Hitbox::GetX, Hitbox::GetY.
std::vector< Bullet * > * Bullets::GetBullets()
References bullets.
Bullets::~Bullets()
References bullets.