Player
bool Player::up
Referenced by calculatePosition, SetUp.
bool Player::down
Referenced by calculatePosition, SetDown.
bool Player::left
Referenced by calculatePosition, SetLeft.
bool Player::right
Referenced by calculatePosition, SetRight.
bool Player::shooting
Referenced by PlayerShot, SetShooting.
Player::Player()
Player::Player(const char *filename, int radius, int health)
Player::Player(const char *filename, int radius, int s, int health)
void Player::calculatePosition()
References down, ship::GetSpeed, left, Hitbox::posX, Hitbox::posY, right, up, WindowHeight, WindowWidth.
Referenced by Game::mainloop.
void Player::DrawPlayer(int x, int y, int rotation=0, int scale=1)
References ship::DrawShip.
Referenced by Game::mainloop.
bool Player::CalculateCollisionsForPlayer(Bullets *bullets)
References ship::CalculateCollisions.
Referenced by Game::mainloop.
void Player::PlayerShot(Bullets *bullets, int counter)
References Bullets::AddBullet, GetX, GetY, shooting.
Referenced by Game::mainloop.
void Player::SetUp(bool var)
References up.
Referenced by Game::mainloop.
void Player::SetDown(bool var)
References down.
Referenced by Game::mainloop.
void Player::SetLeft(bool var)
References left.
Referenced by Game::mainloop.
void Player::SetRight(bool var)
References right.
Referenced by Game::mainloop.
void Player::SetShooting(bool var)
References shooting.
Referenced by Game::mainloop.
double Player::GetX()
References Hitbox::posX.
Referenced by Game::mainloop, PlayerShot.
double Player::GetY()
References Hitbox::posY.
Referenced by Game::mainloop, PlayerShot.
Player::~Player()